name: 'Branch Name Default'
description: 'Get incorrect branch name'
author: 'Team Devops'
inputs:
  allowed_branch_list:
    required: false
    description: 'Add list branch validate, separeted with ,'
    default: 'main,release,feature,devops,hotfix,fix,dependabot,revert,story,exp'
  payload:
    required: false
    description: 'Create payload to slack message'
  channel_id:
    required: false
    description: 'Add chanel id slack'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'arrow-right-circle'  
  color: 'blue'
